In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6]] , np.int16)

In [3]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [4]:
x[0]

array([1, 2, 3], dtype=int16)

In [5]:
x[0][0]

1

In [8]:
x[0:1,0:1]

array([[1]], dtype=int16)

In [9]:
x[0:1,:]

array([[1, 2, 3]], dtype=int16)

In [10]:
x[1]

array([4, 5, 6], dtype=int16)

In [11]:
x[1][1]

5

In [12]:
x[1][2]

6

In [13]:
x[0:2,0:1]

array([[1],
       [4]], dtype=int16)

In [14]:
x[:,0]

array([1, 4], dtype=int16)